### PR TITLE
Fix various issues around internationalised landing and overview pages

### LINKED ISSUE #2639: Change the way how an i18n index page shows its contents
Currently, index pages are displayed based on the contents in `tos.yaml`. For example, privacy sandbox page is rendered based on `/site/_data/i18n/docs/privacy-sandbox.yml` and it's at https://developer.chrome.com/docs/privacy-sandbox/

When a user goes to an i18n page, in the above case https://developer.chrome.com/ja/docs/privacy-sandbox/, they see articles that are already translated (the translated markdown exists) but without `title` property specified in the `tos.yaml`.

Issue 1: I would like to see all articles regardless of translation status. This will help the audience not to miss important contents but not translated yet.

Issue 2: By looking at the current behavior, titles displayed in https://developer.chrome.com/ja/docs/privacy-sandbox/ are translated even if the entry in `tos.yaml` doesn't have a `title` property. I presume this is because 11ty can extract the translated title from the markdown and apply that to the index page. If that is possible, I would not provide string resources as much as possible. This will help:

* Avoid duplicate translation
* It's a good indicator for the audience whether it's translated or not. If the title is in English, they can guess that it's not translated yet.
* Reduce amount of effort to translate

### PR DESCRIPTION
**Pull request by matthiasrohmer**
Fixes #2639 and #2004.

This PR makes the `internalFind` method which is used when building navigations/page lists fallback to then English language directory if there is no match for a specified locale. It also makes a similar change for the method that creates the blog and articles overview by using the English tree as a base and merging in the localized tree.

Additionally it removes the translated strings from the YAMLs where better strings already exist on the page's frontmatter.

/cc @agektmr

### CODE REVIEW

File: site/_utils/addCollectionByDirectory.js [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+ * alongside untranslated ones.
+ */
+
+const path = require('path');
+const {filterOutDrafts} = require('./drafts');
+
+const defaultLocale = 'en';
+
+function addCollectionByDirectory(config, locale, dir) {
+  config.addCollection(`${dir}-${locale}`, collections => {
```
Comment (devnook) [inline site/_utils/addCollectionByDirectory.js:30]: I think this function should be defined in the _collections folder: https://github.com/GoogleChrome/developer.chrome.com/tree/main/site/_collections and then the addCollection call can stay in the main eleventy file.

File: site/_utils/addCollectionByDirectory.js [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+    // sense in trying to merge them, just return the English articles then
+    if (localeCollection.length === 0) {
+      return baseCollection;
+    }
+
+    // Otherwise walk through the English collection while looking
+    // for matches in the locale collection and if it's a match, replace
+    let localeIndex = 0;
+    let collection = [];
+    for (let index = 0; index < baseCollection.length; index++) {
```
Comment (devnook) [inline site/_utils/addCollectionByDirectory.js:65]: This got complex enough to deserve a test.

File: site/_utils/addCollectionByDirectory.js [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+      const item = baseCollection[index];
+      const localizedItem = localeCollection[localeIndex];
+
+      if (item.fileSlug === localizedItem.fileSlug) {
+        collection.push(localeCollection[localeIndex]);
+        localeIndex++;
```
Comment (devnook) [inline site/_utils/addCollectionByDirectory.js:71]: If first 3 items in baseCollection are a miss, then on 4th iteration index=3 but localeIndex=0 and they get out of sync. You'll be pushing wrong article to the collection array.

File: site/_utils/addCollectionByDirectory.js [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+      } else {
+        collection.push(baseCollection[index]);
+      }
+
+      // If there are no items left to potentially localize then simply
+      // append the rest of the articles and stop
+      if (localeIndex === localeCollection.length) {
+        collection = collection.concat(baseCollection.slice(index + 1));
```
Comment (devnook) [inline site/_utils/addCollectionByDirectory.js:79]: 11ty collections are sorted by default (by date *I think*), you'll loose this behavior here. There might be parts of the code that silently rely on this characteristic, so maybe worth seorting the collection here.

**Review by devnook — CHANGES_REQUESTED** [review]
Thanks @matthiasrohmer ! Let's also add a test for this collection please.

File: site/_utils/addCollectionByDirectory.js (hunk 3 above)
Comment (matthiasrohmer) [reply site/_utils/addCollectionByDirectory.js:71]: Clarified offline. The code works as intended under the assumption that `localeCollection` has the same order as `baseCollection` and is a translated subset of it, not containing any original items.

File: site/_utils/addCollectionByDirectory.js (hunk 4 above)
Comment (matthiasrohmer) [reply site/_utils/addCollectionByDirectory.js:79]: Clarified offline. The code works as intended under the assumption that `localeCollection` has the same order as `baseCollection` and is a translated subset of it, not containing any original items.

Agreed to only rely on slugs for matching instead of on date order as well.

**Comment by devnook** [comment]
Hi @matthiasrohmer , where are we standing with this Pr?

**Review by devnook — APPROVED** [review]
