### PR TITLE
Events page fixes

### LINKED ISSUE #3853: The bold font on tabs make the text jump when a tab gets selected
Leftover from #3786 

The bold font on tabs make the text jump when a tab gets selected:
Screenshot 2022-09-28 at 20 34 41

### LINKED ISSUE #3854: The tag pill highlights and gets underline on hover, which suggests it is a link
The tag pill highlights and gets underline on hover, which suggests it is a link, but clicking on it does nothing. We should remove interactivity from it, or attach an action on click.

### LINKED ISSUE #3855: We need to index events and expose them in search.
We need to index events and expose them in search.

### LINKED ISSUE #3863: “See who’s joining” doesn’t make sense for past events.
In the Past events tab, can we update all the CTA buttons universally to “See details”? “See who’s joining” doesn’t make sense for past events.

### LINKED ISSUE #3864: Strings are not translated for events
Strings are not translated in this partial: https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_includes/partials/events-hero.njk

### PR DESCRIPTION
**Pull request by johnrich85**
Fixes #3864
Fixes #3863
Fixes #3855
Fixes #3853 
Fixes #3854

### CODE REVIEW

File: site/_js/web-components/web-tabs.js [hunk 1]
```diff
@@ -88,6 +88,28 @@ export class WebTabs extends BaseElement {
     });
   }
 
+  _getDefaultTab() {
```
Comment (devnook) [inline site/_js/web-components/web-tabs.js:91]: Nit: this is not default tab, but the tab selected via url param. I'd call it _getSelectedTabIndex

**Review by devnook — APPROVED** [review]
